### CREATE
POST http://localhost:3000/task HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1c3Rhdm9nYWxvIiwic3ViIjoiM2QyYzdlNDctODgwNC00ZTdkLWExY2QtNmI5MmRkMTA0YzQ2IiwiaWF0IjoxNzQwNTM0MTY5LCJleHAiOjE3NDA1Mzc3Njl9.rfse59bNYDszeQ3Xvbddk-O8d1IkpKWxffplpIg3HZE
Content-Type: application/json

{
  "title": "Task #1",
  "description": "First task",
  "projectColumnId": "36bb83b5-f94b-47e5-b1ee-fd0a52b2beba"
}